services:
  postgres:
    image: postgres:16
    container_name: finprodpref-db
    environment:
      POSTGRES_DB: finprodpref
      POSTGRES_USER: chris
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./DB:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finprodpref-backend
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/products || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finprodpref-frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 4173:4173
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1g"

volumes:
  postgres-data: